version: "3.8"

services:
  market-mysql:
    image: mysql
    container_name: market-mysql
    env_file:
      - .db-env
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
  market-adminer:
    image: adminer
    depends_on:
      - market-mysql
    ports:
      - "8081:8080"
  market-app:
    build: ./
    depends_on:
      - market-mysql
    env_file:
      - .env
    environment:
      - APP_PORT:${APP_PORT}:8000
      - MYSQL_USER:${MYSQL_USER}:root
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}:password
      - MYSQL_HOST:${MYSQL_HOST}:localhost
      - MYSQL_PORT:${MYSQL_PORT}:3307
    ports:
      - "8001:${APP_PORT}:8000"
